# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craw_ind', '0002_remove_keywordsdata_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordsdata',
            name='keyword',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='keywordsdata',
            name='location',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
