# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craw_ind', '0003_auto_20170321_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='bodystorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexpage', models.CharField(db_index=True, max_length=3)),
                ('pagebody', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'db_table': 'bodystorage',
            },
        ),
    ]
