# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craw_ind', '0003_auto_20170321_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='bodyheads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.CharField(max_length=10)),
                ('bodyum', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'bodyheads',
            },
        ),
    ]
