# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craw_ind', '0004_bodystorage'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bodystorage',
            table='bodystorages',
        ),
    ]
