# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craw_ind', '0004_bodyheads'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bodyheads',
            table='bodyheadum',
        ),
    ]
