# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craw_ind', '0005_auto_20170328_1100'),
        ('craw_ind', '0005_auto_20170409_1847'),
    ]

    operations = [
    ]
